# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Source global definitions
[ -f /etc/bashrc ] && . /etc/bashrc

# Powerline
if [  `tput colors` = "256" ]; then
	/usr/bin/powerline-daemon -q
	POWERLINE_BASH_CONTINUATION=1
	POWERLINE_BASH_SELECT=1
	. /usr/lib/python3.6/site-packages/powerline/bindings/bash/powerline.sh
else
	PS1='[\u@\h \W]\$ '
fi

alias ls='ls --color=auto'

